### ISSUE TITLE
`moveend` event handler is invoked after `result` is triggered

### ISSUE THREAD

**Issue by Erutan409** [mapbox/mapbox-gl-geocoder#131]
My `moveend` handler is being triggered before the map even starts to move to the location I select from the search results.

mapboxgl: **v0.41.0**
geocoder: **v2.1.1**

**Comment by andrewharvey** [comment]
@Erutan409 I suspect this is because of #99, which causes the result event to be fired twice. As part of that the map tries to animate to the location twice (the first one being interrupted by the second).

Interrupting a camera animation with another camera animation in GL JS [causes the moveend event to fire](https://jsbin.com/lubiqoj/edit?html,console,output), hence you're getting the issue you describe.

Unfortunately #99 is not easy to fix for both modern browsers and IE11, so it remains a bug.

If you don't need to support IE11 then you can try https://github.com/mapbox/mapbox-gl-geocoder/issues/99#issuecomment-307981164 and see if that resolves the issue?

**Comment by Erutan409** [comment]
I'll check my code Monday, but I think I solved it with a closure and a brief timeout. It was weird, but necessary.

**Comment by scottsfarley93** [comment]
This was addressed in #229 and will be fixed when version 4 is released.
