### ISSUE TITLE
Feature request: Use of multiple bboxes to limit search results

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-geocoder#132]
It would be nice to be able to use multiple bboxes to limit search results.

Use case: 
For a map there are search results wanted only for some specific areas. 

Example: 
Map of the US, where only certain states are of interest for an application. The map data of the other states provides geographic context only, but is not relevant for the geocoder search results.

**Comment by andrewharvey** [comment]
Since the bbox is just passed upstream to the Mapbox Geocoding API, and since it only accepts one bbox, I'm thinking a better feature here is for the user to pass a large bbox covering all areas they are interested in and support a `map` or `filter` function to gl-geocoder, so client side you can do whatever filtering like point in polygon or based on some attribute returned by the geocoder.

@pathmapper What do you think about that?

**Comment by pathmapper** [comment]
@andrewharvey thanks for the background and your suggestion!

If I understand you right, this sounds even better to me than using multiple bboxes because it would be possible to filter the search results more precise.

A bbox is most of the time only a approximation of the relevant area. Being able to use one or more polygon(s) for filtering what comes from the Mapbox Geocoding API would be perfect.

Regarding filter "based on some attribute returned by the geocode":
Do you mean something like `options.country` or `options.types` which is currently possible when requesting the Mapbox Geocoding API but now filtering what the API returns?

**Comment by andrewharvey** [comment]
> If I understand you right, this sounds even better to me than using multiple bboxes because it would be possible to filter the search results more precise.
> A bbox is most of the time only a approximation of the relevant area. Being able to use one or more polygon(s) for filtering what comes from the Mapbox Geocoding API would be perfect.

That's right, with this approach you can filter by a polygon rather than just an approximation with bbox's. The catch is you're filtering the results post the geocoding API call. Given the API only returns at most 10 results there is a chance that you won't get all the results you should since you're doing the filter post the geocoding API.

> Regarding filter "based on some attribute returned by the geocode":
Do you mean something like options.country or options.types which is currently possible when requesting the Mapbox Geocoding API but now filtering what the API returns?

Yes, pretty much. With a filter function option, you could choose how you want to filter the results. So it could be based on a geometry test if the geocode is within a polygon, or you could filter based on the geocode response attributes such as the region, city, or any other field in the response https://www.mapbox.com/api-documentation/#response-object.

**Comment by andrewharvey** [comment]
@pathmapper Take a look at https://github.com/mapbox/mapbox-gl-geocoder/compare/filter-option for what I mean. The example is the same as the main example but with the filter function added, which in this case ensures results are only from one State in Australia (something not possible to filter with a bbox, though really in this case you should use country, bbox and the filter all together for optimal results).

You could easily do a point in polygon check instead based on the geometry with something like https://github.com/mapbox/which-polygon.

I could polish this up a bit with tests etc and turn it into a PR as I think it has valid use cases.

**Comment by pathmapper** [comment]
@andrewharvey thanks for sharing!

> Given the API only returns at most 10 results there is a chance that you won't get all the results you should since you're doing the filter post the geocoding API.

I don't see this as a problem because the limitation of 10 results is there anyway. The API call itself must be optimised like you described with the available options (country, bbox, type ...) to have a suitable response object for the following filtering.

> I could polish this up a bit with tests etc and turn it into a PR as I think it has valid use cases.

Great! Another use case could be to workaround the restriction, that a bounding box for a geocoding API call cannot cross the 180th meridian. There could be two polygons (east and west of the 180th) for the filter polygon check.

**Comment by andrewharvey** [comment]
I think adding support for multiple bbox's via multiple Geocoding API requests would increase complexity and I don't think it's worth it, given the main use case of limiting results to a non-polygon area of interest can now be achieved client side with the filter option (either filtering by a property in the Geocoding response, or via a point in polygon test) I'm going to close this ticket.

**Comment by pathmapper** [comment]
@andrewharvey thanks! Is there any documentation how to use the different filter options?

**Comment by andrewharvey** [comment]
>@andrewharvey thanks! Is there any documentation how to use the different filter options?

@pathmapper See #135
