### ISSUE TITLE
result event isn't invoked

### ISSUE THREAD

**Issue by johnfrancisgit** [mapbox/mapbox-gl-geocoder#263]
In all versions from v4.0.0 the result event isn't triggered. Earlier versions work as expected.

**Comment by scottsfarley93** [comment]
hey @johnfrancisgit thanks for the issue! What version of mapbox-gl-geocoder are you using and what browser are you running on?

**Comment by johnfrancisgit** [comment]
The issue starts from v4.0.0 and I'm using Firefox

**Comment by scottsfarley93** [comment]
@johnfrancisgit could you provide a minimally reproducing example?

**Comment by johnfrancisgit** [comment]
Hey @scottsfarley93 Sure, here is a JSFiddle using v4.0.0 where the result event is not triggered. If you change the resource to use e.g v3.1.6, the result event is triggered as expected on search.

**Comment by scottsfarley93** [comment]
hey @johnfrancisgit thanks for providing the JSfiddle. I was able to dig into this a bit this morning. I believe that this is due to a version mismatch between mapbox-gl-geocoder and mapbox-gl-js. As noted on the [changelog](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/CHANGELOG.md#breaking-changes-%EF%B8%8F) the new version of the geocoder is compatible only with mapbox-gl-js version 0.47.0 and above. This version change is required to support adding markers on the map upon result selection. 

I looks from your fiddle like your mapbox-gl-js version is at 0.42.0. In the console, there's a `Uncaught TypeError: Cannot read property 'add' of undefined` error generated when adding the marker, blocking the emission of a result event. 

I think there's two options:
1. Upgrade mapbox-gl-js to version 0.47.0 or above. This will satisfy the minimum version requirement and will prevent the error from occurring [fiddle](https://jsfiddle.net/exnk2rbf/). 
2. Set `marker:false` in the constructor options when creating a new geocoder [fiddle](https://jsfiddle.net/3preqnat/4/), which will prevent placing a marker on the map when a result is selected. 

Both of these cases should emit a `result` event.

**Comment by johnfrancisgit** [comment]
Oh, my bad. Completely overlooked that. Using a more recent version of mapbox-gl-js does indeed fix the issue. Thanks @scottsfarley93
