### ISSUE TITLE
geocoding/v5 API: MapiError 422 with coma query

### ISSUE THREAD

**Issue by qnp** [mapbox/mapbox-gl-geocoder#274]
Related to #168

Using Mapbox API geocoding/v5 with the `limit` param (`limit` option from *mapbox-gl-geocoder*), when you make a query with a coma whitout anything or with spaces after, such as:
```
42, 
```
Mapbox API returns a `422 MapiError` with 
```
{ message: limit must be combined with a single type parameter when reverse geocoding }
```
Working example:
https://codepen.io/ekqnp/pen/MdbrEx
This is also happening in the example proposed by Mapbox:
https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/

The only solution I found to avoid this error is to set `limit: false` and to handle the limit myself front-side.

Any ideas about it ?

**Comment by qnp** [comment]
FYI to handle limit front-side, the only way I found is:
```
geocoderControl.on('results', items => items.features = items.features.slice(0, LIMIT));
```

**Comment by andrewharvey** [comment]
I think ultimately this is due to the fact that the Geocoding API doesn't have a different forward and reverse geocoding endpoint, so it has to guess for each query if it is a forward or reverse geocode, and you can't force it to be one or the other.

I'm trying to get an understanding of what the user expects here... Are they forward geocoding `42,` do you have an example of what they might be searching for to enter that? Or are they trying to search by coordinates but just haven't finished tying the whole query yet?

I guess the fix within mapbox-gl-geocoder is to determine before it sends the request if it would be problematic and just avoid that request. So just do nothing here and wait for the user to enter more text.

What do you think?

**Comment by qnp** [comment]
The use case of such entry `42, ` can be either:
- Direct input of coordinates and not finished typing the whole yet, as you suggest
- Some people that (it is the case in France, and may be in other countries) type a coma after the number of the street, such as: `42, rue de Chartres, 75018, Paris`, but again did not finished typing the whole yet.

This fix within *mapbox-gl-geocoder* will indeed **workaround** the issue, but anyone who's hitting Mapbox geocoding API will have the problem. Maybe should I adress this issue to Mapbox API team ? (I did not find any github repo on it...)

**Comment by rassokhina-e** [comment]
Hello guys! Do you have any updates for the issue?
I'm experiencing the same one.

**Comment by asheemmamoowala** [comment]
This is also the source of 100s of unhandled exceptions reported to sentry from the https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ example.

Given that the plugin is providing a UI element, it is a good practice to handle known response codes from the service and surface to the user (or eat it) as the situation warrants.

**Comment by andrewharvey** [comment]
> Given that the plugin is providing a UI element, it is a good practice to handle known response codes from the service and surface to the user (or eat it) as the situation warrants.

I think in this case the `422 MapiError` with message `{ message: limit must be combined with a single type parameter when reverse geocoding }` should be silently handled by the plugin, any other error should be surfaced (other errors are already surfaced, like no connection to the server).

Originally I thought try to predict this and not make the request, but if we can future proof so if this changes in the API we don't need to update anything here that would be ideal, so I think just handle the error is best.
