### ISSUE TITLE
Map is not focusing correctly for Tokyo 

### ISSUE THREAD

**Issue by girishts** [mapbox/mapbox-gl-geocoder#283]
Hi,

After Searching Tokyo using geocoder, if we select the result from the autocomplete and if we try to focus to Tokyo using the search results ,it is not focusing properly. For other cities it is working fine.

        map.flyTo(
          {center: [longitude, latitude]
          });

**Comment by martinburch** [comment]
I agree, there is a problem with the `Tokyo Prefecture, Japan` bounding box, unless Tokyo happens to include something way out at sea. Even still, this needs to be investigated, because San Francisco's zoom box is alright (that is, it doesn't include the Farallon islands).
![image](https://user-images.githubusercontent.com/2335284/59844389-aa94f180-9352-11e9-9266-36776b2ce63f.png)

I have reported this issue via the feedback site.
https://labs.mapbox.com/geocoder-feedback/#search=region.15637623541111140
(click on the first search result, `1. 東京都`, to see the bounding box bug.)

**Comment by scottsfarley93** [comment]
Since this is a data issue rather than a mapbox-gl-geocoder issue, I think we can close this out. Thanks @martinburch for reporting the bug via the feedback site.
