### ISSUE TITLE
Dutch postalcode format support

### ISSUE THREAD

**Issue by haveanicerepo** [mapbox/mapbox-gl-geocoder#288]
Dutch postalcodes contains 4 digits and 2 letters. 
When entering 4 digits, it finds the global postalcode location, but when you add 2 letters (which corresponds to a street) the response doenst return the right location.

For example: 1012 returns a general postalcode location in Amsterdam. But when you enter 1012 AW it returns totally different results (different cities even). But it should return a specific location within the 1012 postalcode area.

Here is a mapbox-playground with dutch country filtering: [mapbox-search playground](https://docs.mapbox.com/search-playground/#{%22url%22:%22%22,%22index%22:%22mapbox.places%22,%22staging%22:false,%22onCountry%22:true,%22onType%22:true,%22onProximity%22:true,%22onBBOX%22:true,%22onLimit%22:true,%22onLanguage%22:true,%22countries%22:[{%22name%22:%22Netherlands%22,%22code%22:%22nl%22}],%22proximity%22:%22%22,%22typeToggle%22:{%22country%22:false,%22region%22:false,%22district%22:false,%22postcode%22:true,%22locality%22:false,%22place%22:false,%22neighborhood%22:false,%22address%22:true,%22poi%22:false},%22types%22:[%22address%22,%22postcode%22],%22bbox%22:%22%22,%22limit%22:%22%22,%22autocomplete%22:true,%22languages%22:[],%22languageStrict%22:false,%22onDebug%22:false,%22selectedLayer%22:%22%22,%22debugClick%22:{},%22localsearch%22:false,%22query%22:%22%22})

Could Dutch postalcodes be supported?

**Comment by RichardLindhout** [comment]
Heavily depending on this. Or else I need to do a request just for the postal code to Google Maps :(

**Comment by andrewharvey** [comment]
@haveanicerepo @RichardLindhout If you're seeing this issue in the Mapbox Search Playground then it's more likely an issue in the Mapbox Geocoding API, which you'll need to raise with [Mapbox Support](https://support.mapbox.com/hc/en-us).

This open source project is the search control (user interface) for Mapbox GL JS, so it's the right place to report issues with the how that search control works, but not normally the search results.

Because we can't address this here in the control, I'll close this issue, but I do recommend you follow up with Mapbox Support if it's relating to the Geocoding API.

**Comment by RichardLindhout** [comment]
That's right. I'm was doing it right know. Thanks for your response!

**Comment by RichardLindhout** [comment]
@haveanicerepo I have asked this to support but no answer yet. Also on Stackoverflow and an engineer commented on the question!

https://stackoverflow.com/questions/57607128/dutch-postalcode-in-mapbox-geocoding-api
