### ISSUE TITLE
What-Three-Words support

### ISSUE THREAD

**Issue by dburnsii** [mapbox/mapbox-gl-geocoder#290]
This up and coming geocoding mechanism would be a great addition to the Geocoder functionality:

https://what3words.com/

Both Ford and Mercedes are using these in their vehicles, and Dominoes has it built into their app. This provides a good case to integrate into the existing Mapbox Geocoder functionality.

**Comment by andrewharvey** [comment]
With #157 and similar to the example at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-accept-coordinates/ you could implement this yourself client side.

So as far as I'm concerned this would be something people who want would implement on their own.

Since this issue tracker is for the MapboxGeocoder client library, not the Mapbox Geocoding API, I don't see anything actionable here to implement.
