### ISSUE TITLE
Mapbox reverse geocode giving wrong address for different zoom level.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-geocoder#342]
We have noticed a bug while reverse geocoding, returning wrong addresses for different zoom levels

**Steps to reinvent:** 

1. Open mapbox geocode playground.
2. Search with this coordinate "-117.93763120991036,33.992568759676075".
3. Click on the house and check the dropdown for address. 
4. The address will be changed if we click on different location on the same house.

 **FYI** --> This is occurring only in particular locations. 

Tested this is mapbox playground and found the same issue,  Please refer the attached video for more info.

[https://www.dropbox.com/s/rkicjq7hhe1dnoy/Mabox%20geocode%20issue.mov?dl=0](url)

**Comment by andrewharvey** [comment]
Hi this repository is for the search control for Mapbox GL JS, it looks like this is an issue with the Geocoding API this project relies on. [Mapbox Support](https://www.mapbox.com/support) is the best contact for reporting issues with the Geocoding API. Since this is not something we can address in this project I'll close the issue.

**Comment by ThiyagarajanShivSankaran** [comment]
@andrewharvey Sorry about the confusion.
