### ISSUE TITLE
Geocoder not finding streets in Serbia

### ISSUE THREAD

**Issue by andreolikalcopoli** [mapbox/mapbox-gl-geocoder#346]
I am having a lot of problems trying to find coordinates of some streets in Serbia. However, I came to the conclusion that Mapbox Geocoder is not supporting Serbia streets. Is there a way to pay for it, or I am just doing something wrong?

**Comment by andrewharvey** [comment]
Hi this repository is for the search control for Mapbox GL JS, it looks like this is a question about Geocoding API this project relies on. Mapbox Support is the best contact for reporting issues with the Geocoding API. Since this is not something we can address in this project I'll close the issue.
