### ISSUE TITLE
v4.0.0 is still tagged as latest release ...

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-geocoder#395]
... but there are more recent releases:
https://github.com/mapbox/mapbox-gl-geocoder/releases

![grafik](https://user-images.githubusercontent.com/20856381/92609061-68890000-f2b6-11ea-810d-ec900e65c6b3.png)

**Comment by andrewharvey** [comment]
Right, so I just learnt from this that GitHub has a Releases feature, but releases aren't made automatically from tags, you need to go in and created them through GitHub from the tag.

So this could be something that is built into the release process, but it's just more effort to do so hasn't been done. Otherwise you can keep track of releases through npm published versions.

**Comment by VladislavMedved** [comment]
Currently the latest release is v.5.0.0 so seems to be fixed
<img width="279" alt="Screen Shot 2023-01-04 at 2 28 56 PM" src="https://user-images.githubusercontent.com/11231287/210545711-86976683-46ab-4149-b8df-f234bf4a8b58.png">
