### ISSUE TITLE
setInput bug?

### ISSUE THREAD

**Issue by anatolysukhanov** [mapbox/mapbox-gl-geocoder#401]
https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#setinput is used to only populate the input (at least 4.5.1).

So, for intstance, if I call

    geocoder.setInput("New York")

I get this:

![image](https://user-images.githubusercontent.com/7021042/99783416-74513800-2b2b-11eb-991c-f15bb1c377a0.png)

but in the latest version (4.7.0) it has changed and now it shows the results dropdown:

![image](https://user-images.githubusercontent.com/7021042/99783980-31dc2b00-2b2c-11eb-9569-2e0d593f73bb.png)

Is that a bug or intentional new behaviour?

**Comment by zokioki** [comment]
This behavior was recently introduced via https://github.com/mapbox/mapbox-gl-geocoder/pull/345.

**Comment by antony** [comment]
Just stumbled across this as well. It's hugely problematic if you are trying to prefill the location picker with the current value of the field. You now have only two choices to show:

1. A blank field
2. A dropdown open in the middle of your page

I'm certainly eager to see https://github.com/mapbox/mapbox-gl-geocoder/pull/425 merged in order to allow better control over this feature

**Comment by nx** [comment]
I encountered the same problem. It's indeed a bit confusing that `setInput()` leads to new results being shown.

This did the trick for me. It's not ideal, but there doesn't seem to be a better solution.
```javascript
geocoder.current._inputEl.value = value;
```

**Comment by christopherstyles** [comment]
This also works, but am looking forward to #425 as well 😄 

```javascript
const inputElements = document.getElementsByClassName(
  'mapboxgl-ctrl-geocoder--input',
);

if (inputElements.length > 0) {
  inputElements[0].value = "New York";
}
```
