### ISSUE TITLE
Uncaught TypeError: nanoid is not a function

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-geocoder#443]
I'm getting

Uncaught TypeError: nanoid is not a function
    at MapboxEventManager.generateSessionID

Looking at the code, and some other reports of issues like this, I suspect the code in events.js should be doing:

```
var { nanoid } = require('nanoid')
```

But then I don't understand why this works in the mapbox examples??

**Comment by justisb** [comment]
I think this may actually be resolved by PR https://github.com/mapbox/mapbox-gl-geocoder/pull/447, which updates nanoid to the latest version. Though I don't think the error is the fault of mapbox-gl-geocoder per se.

Nano ID 3.0.0 changed its default exports so that a `var nanoid = require('nanoid').nanoid` would be required, as you suggest. This package specifies an older 2.x.x version as a dependency, so this should not be an issue.  However, for those experiencing the error, I bet there is some package misconfiguration on their end, such as forcing the resolution of "nanoid" to a 3+ version incompatible with mapbox-gl-geocoder.

I came across this and submitted the PR because I wanted to fix the security warning present in older versions of Nano ID.
